# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "test_branch" ]
  pull_request:
    branches: [ "test_branch" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install pandas
        pip install scikit-learn
        pip install altair
        pip install altair_saver
        pip install jupyter-book
        pip install matplotlib
        pip install pyppeteer
        pip install docopt-ng
        pip install vl-convert-python
    - name: Test with pytest
      run: |
        cd src && python fetch_dataset.py
        python pre_process.py
        python eda.py
        python model.py
